/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.BatchClassController;
import controllers.BatchController;
import controllers.ClassesController;
import controllers.RoomController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Employee;
import org.hibernate.Hibernate;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;

/**
 *
 * @author gerydanu
 */
public class BatchClassView extends javax.swing.JInternalFrame {
    private SessionFactory factory = HibernateUtil.getSessionFactory();
    private BatchClassController bcc = new BatchClassController(factory);
    private BatchController bc = new BatchController(factory);
    private ClassesController csc = new ClassesController(factory);
    private RoomController rc = new RoomController(factory);
    DefaultTableModel myTableModel = new DefaultTableModel();
    private List<models.BatchClass> batchClassList= new ArrayList<>();
    private List<models.Batch> batchList= new ArrayList<>();
    private List<models.Classes> classTypeList= new ArrayList<>();
    private List<models.Room> roomList= new ArrayList<>();

    /**
     * Creates new form AspectView
     */
    public BatchClassView() {
        initComponents();
        tableData(bcc.getAll());
    }
    
    private void tableData(List<models.BatchClass> batchClass) {
        Object[] columnNames = {"ID", "Trainer", "Batch", "Classes", "Room"};
        Object[][] data = new Object[batchClass.size()][columnNames.length];
        for (int i = 0; i < data.length; i++) {
            data[i][0] = (i + 1);
            data[i][1] = batchClass.get(i).getId();
            data[i][2] = batchClass.get(i).getTrainer();
            data[i][3] = batchClass.get(i).getBatch();
            data[i][3] = batchClass.get(i).getClasses();
            data[i][3] = batchClass.get(i).getRoom();

        }
        myTableModel = new DefaultTableModel(data, columnNames);
        tbBatchClass.setModel(myTableModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleBatchClass = new javax.swing.JLabel();
        pnBatchClass = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        lblTrainer = new javax.swing.JLabel();
        cbTrainer = new javax.swing.JComboBox<>();
        lblBatch = new javax.swing.JLabel();
        cbBatch = new javax.swing.JComboBox<>();
        lblClass = new javax.swing.JLabel();
        cbClass = new javax.swing.JComboBox<>();
        lblRoom = new javax.swing.JLabel();
        cbRoom = new javax.swing.JComboBox<>();
        pnTable = new javax.swing.JPanel();
        scpBatchClass = new javax.swing.JScrollPane();
        tbBatchClass = new javax.swing.JTable();

        setClosable(true);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        lblTitleBatchClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleBatchClass.setText("BATCH CLASS");
        getContentPane().add(lblTitleBatchClass, java.awt.BorderLayout.PAGE_START);

        pnBatchClass.setLayout(new java.awt.GridLayout(5, 2, 5, 5));

        lblID.setText("ID");
        pnBatchClass.add(lblID);
        pnBatchClass.add(tfID);

        lblTrainer.setText("Trainer");
        pnBatchClass.add(lblTrainer);

        pnBatchClass.add(cbTrainer);

        lblBatch.setText("Batch");
        pnBatchClass.add(lblBatch);

        pnBatchClass.add(cbBatch);

        lblClass.setText("Class");
        pnBatchClass.add(lblClass);

        pnBatchClass.add(cbClass);

        lblRoom.setText("Room");
        pnBatchClass.add(lblRoom);

        pnBatchClass.add(cbRoom);

        getContentPane().add(pnBatchClass, java.awt.BorderLayout.CENTER);

        tbBatchClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Trainer", "Batch", "Class", "Room"
            }
        ));
        scpBatchClass.setViewportView(tbBatchClass);

        javax.swing.GroupLayout pnTableLayout = new javax.swing.GroupLayout(pnTable);
        pnTable.setLayout(pnTableLayout);
        pnTableLayout.setHorizontalGroup(
            pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scpBatchClass, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        );
        pnTableLayout.setVerticalGroup(
            pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
            .addGroup(pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTableLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scpBatchClass, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(pnTable, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbBatch;
    private javax.swing.JComboBox<String> cbClass;
    private javax.swing.JComboBox<String> cbRoom;
    private javax.swing.JComboBox<String> cbTrainer;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblTitleBatchClass;
    private javax.swing.JLabel lblTrainer;
    private javax.swing.JPanel pnBatchClass;
    private javax.swing.JPanel pnTable;
    private javax.swing.JScrollPane scpBatchClass;
    private javax.swing.JTable tbBatchClass;
    private javax.swing.JTextField tfID;
    // End of variables declaration//GEN-END:variables
}
