/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author gerydanu
 */
public class CreateAccountView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CreateAccountView
     */
    public CreateAccountView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBootcamp = new javax.swing.JPanel();
        pnRegister = new javax.swing.JPanel();
        pnRegister1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblBirthPlace = new javax.swing.JLabel();
        lblBirthDate = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblReligion = new javax.swing.JLabel();
        lblMaritalStatus = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfBirthPlace = new javax.swing.JTextField();
        tfBirthDate = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox<>();
        cbReligion = new javax.swing.JComboBox<>();
        cbMaritalStatus = new javax.swing.JComboBox<>();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblProvince = new javax.swing.JLabel();
        lblDistrict = new javax.swing.JLabel();
        lblSubdistrict = new javax.swing.JLabel();
        lblVillage = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfPhone = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        cbProvince = new javax.swing.JComboBox<>();
        cbDistrict = new javax.swing.JComboBox<>();
        cbSubdistrict = new javax.swing.JComboBox<>();
        cbVillage = new javax.swing.JComboBox<>();
        lblOnboardDate = new javax.swing.JLabel();
        lblHiringLocation = new javax.swing.JLabel();
        tfOnboardDate = new javax.swing.JTextField();
        tfHiringLocation = new javax.swing.JTextField();
        lblSecurityQuestion = new javax.swing.JLabel();
        lblSecurityAnswer = new javax.swing.JLabel();
        tfSecurityQuestion = new javax.swing.JTextField();
        tfSecurityAnswer = new javax.swing.JTextField();
        btRegister = new javax.swing.JButton();

        setClosable(true);
        setTitle("Create Account");
        setToolTipText("");

        pnBootcamp.setBackground(new java.awt.Color(0, 169, 255));
        pnBootcamp.setLayout(new java.awt.BorderLayout());

        pnRegister.setBackground(new java.awt.Color(63, 191, 255));
        pnRegister.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 15, 30, 15));
        pnRegister.setName(""); // NOI18N

        pnRegister1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnRegister1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setText("ID");
        pnRegister1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, -1));

        lblName.setText("Name");
        pnRegister1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, -1));

        lblBirthPlace.setText("Birth Place");
        pnRegister1.add(lblBirthPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, -1));

        lblBirthDate.setText("Birth Date");
        pnRegister1.add(lblBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, -1));

        lblGender.setText("Gender");
        pnRegister1.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, -1));

        lblReligion.setText("Religion");
        pnRegister1.add(lblReligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, -1));

        lblMaritalStatus.setText("Marital Status");
        pnRegister1.add(lblMaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, -1));
        pnRegister1.add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 200, -1));
        pnRegister1.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 200, -1));
        pnRegister1.add(tfBirthPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 200, -1));
        pnRegister1.add(tfBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 200, -1));

        pnRegister1.add(cbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 200, -1));

        pnRegister1.add(cbReligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 200, -1));

        pnRegister1.add(cbMaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 200, -1));

        lblEmail.setText("E-mail");
        pnRegister1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 60, -1));

        lblPhone.setText("Phone");
        pnRegister1.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 60, -1));

        lblAddress.setText("Address");
        pnRegister1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 60, -1));

        lblProvince.setText("Province");
        pnRegister1.add(lblProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 60, -1));

        lblDistrict.setText("District");
        pnRegister1.add(lblDistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 60, -1));

        lblSubdistrict.setText("Subdistrict");
        pnRegister1.add(lblSubdistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 60, -1));

        lblVillage.setText("Village");
        pnRegister1.add(lblVillage, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 60, -1));
        pnRegister1.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 260, -1));
        pnRegister1.add(tfPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 260, -1));
        pnRegister1.add(tfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 260, -1));

        pnRegister1.add(cbProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 260, -1));

        pnRegister1.add(cbDistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 260, -1));

        pnRegister1.add(cbSubdistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 260, -1));

        pnRegister1.add(cbVillage, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 260, -1));

        lblOnboardDate.setText("Onboard Date");
        pnRegister1.add(lblOnboardDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, -1));

        lblHiringLocation.setText("Hiring Location");
        pnRegister1.add(lblHiringLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, -1));
        pnRegister1.add(tfOnboardDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 190, 30));
        pnRegister1.add(tfHiringLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 190, 30));

        lblSecurityQuestion.setText("Security Question");
        pnRegister1.add(lblSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 90, -1));

        lblSecurityAnswer.setText("Security Answer");
        pnRegister1.add(lblSecurityAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 90, -1));
        pnRegister1.add(tfSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 250, 30));
        pnRegister1.add(tfSecurityAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 250, 30));

        btRegister.setText("Register");
        btRegister.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });
        pnRegister1.add(btRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 110, 30));

        javax.swing.GroupLayout pnRegisterLayout = new javax.swing.GroupLayout(pnRegister);
        pnRegister.setLayout(pnRegisterLayout);
        pnRegisterLayout.setHorizontalGroup(
            pnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnRegister1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnRegisterLayout.setVerticalGroup(
            pnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRegister1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pnBootcamp.add(pnRegister, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnBootcamp, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        // register code
    }//GEN-LAST:event_btRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegister;
    private javax.swing.JComboBox<String> cbDistrict;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbMaritalStatus;
    private javax.swing.JComboBox<String> cbProvince;
    private javax.swing.JComboBox<String> cbReligion;
    private javax.swing.JComboBox<String> cbSubdistrict;
    private javax.swing.JComboBox<String> cbVillage;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblBirthPlace;
    private javax.swing.JLabel lblDistrict;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHiringLocation;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMaritalStatus;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOnboardDate;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblProvince;
    private javax.swing.JLabel lblReligion;
    private javax.swing.JLabel lblSecurityAnswer;
    private javax.swing.JLabel lblSecurityQuestion;
    private javax.swing.JLabel lblSubdistrict;
    private javax.swing.JLabel lblVillage;
    private javax.swing.JPanel pnBootcamp;
    private javax.swing.JPanel pnRegister;
    private javax.swing.JPanel pnRegister1;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfBirthDate;
    private javax.swing.JTextField tfBirthPlace;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfHiringLocation;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfOnboardDate;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfSecurityAnswer;
    private javax.swing.JTextField tfSecurityQuestion;
    // End of variables declaration//GEN-END:variables
}
