/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ClassesController;
import controllers.EmployeeController;
import controllers.ErrorBankController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Classes;
import models.Employee;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;

/**
 *
 * @author gerydanu
 */
public class ErrorBankView extends javax.swing.JInternalFrame {
    private SessionFactory factory = HibernateUtil.getSessionFactory();
    private ClassesController csc = new ClassesController(factory);
    private EmployeeController emc = new EmployeeController(factory);
    private ErrorBankController ebc = new ErrorBankController(factory);
    DefaultTableModel myTableModel = new DefaultTableModel();
    private List<models.Classes> classTypeList= new ArrayList<>();
    private List<models.Employee> employeeList = new ArrayList<>();
    private List<models.ErrorBank> errorBankList = new ArrayList<>();

    /**
     * Creates new form AspectView
     */
    public ErrorBankView() {
        initComponents();
        showClass();
        showEmployee();
        tableErrorBank(ebc.getAll());
    }
    
    
    void showClass() {
//        for (Lesson lesson : lessonList) cbLesson.addItem(lesson.getName());
        for (Classes classes : csc.getAll()) {
            cbClasses.addItem(classes.getName());
        }
    }
    
    void showEmployee() {
//        for (Lesson lesson : lessonList) cbLesson.addItem(lesson.getName());
        for (Employee employee : emc.getAll()) {
            cbEmployee.addItem(employee.getName());
        }
    }
    
    private void tableErrorBank(List<models.ErrorBank> errorBank) {
        Object[] columnNames = {"No.", "ID", "Submit Date", "Description", "Solution", "Class", "Employee"};
        Object[][] data = new Object[errorBank.size()][columnNames.length];
        for (int i = 0; i < data.length; i++) {
            data[i][0] = (i + 1);
            data[i][1] = errorBank.get(i).getId();
            data[i][2] = errorBank.get(i).getSubmitdate();
            data[i][3] = errorBank.get(i).getDescription();
            data[i][4] = errorBank.get(i).getSolution();
            data[i][5] = errorBank.get(i).getClasses().getName();
            data[i][6] = errorBank.get(i).getEmployee().getName();

        }
        myTableModel = new DefaultTableModel(data, columnNames);
        tbErrorBank.setModel(myTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCenter = new javax.swing.JPanel();
        pnErrorBank = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        lblSubmitDate = new javax.swing.JLabel();
        tfSubmitDate = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        tfDescription = new javax.swing.JTextField();
        lblSolution = new javax.swing.JLabel();
        tfSolution = new javax.swing.JTextField();
        lblClasses = new javax.swing.JLabel();
        cbClasses = new javax.swing.JComboBox<>();
        lblEmployee = new javax.swing.JLabel();
        cbEmployee = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btInsert = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        scpErrorBank = new javax.swing.JScrollPane();
        tbErrorBank = new javax.swing.JTable();

        setClosable(true);
        setTitle("Error Bank");
        setMinimumSize(new java.awt.Dimension(750, 550));
        setPreferredSize(new java.awt.Dimension(750, 550));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        pnCenter.setBackground(new java.awt.Color(153, 255, 153));
        pnCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        pnErrorBank.setBackground(new java.awt.Color(153, 255, 153));
        pnErrorBank.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setText("ID");
        pnErrorBank.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 70, 30));
        pnErrorBank.add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 1, 180, 30));

        lblSubmitDate.setText("Submit Date");
        pnErrorBank.add(lblSubmitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 70, 30));
        pnErrorBank.add(tfSubmitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 40, 180, 30));

        lblDescription.setText("Description");
        pnErrorBank.add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 70, 30));
        pnErrorBank.add(tfDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 79, 480, 30));

        lblSolution.setText("Solution");
        pnErrorBank.add(lblSolution, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 70, 30));
        pnErrorBank.add(tfSolution, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 118, 480, 30));

        lblClasses.setText("Class");
        pnErrorBank.add(lblClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 70, 30));

        cbClasses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbClassesMouseClicked(evt);
            }
        });
        pnErrorBank.add(cbClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 180, 30));

        lblEmployee.setText("Employee");
        pnErrorBank.add(lblEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 70, 30));

        cbEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbEmployeeMouseClicked(evt);
            }
        });
        pnErrorBank.add(cbEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 180, 30));
        pnErrorBank.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 560, 34));

        btInsert.setText("Insert");
        btInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btInsertMouseClicked(evt);
            }
        });
        pnErrorBank.add(btInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 70, 34));

        btDelete.setText("Delete");
        btDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDeleteMouseClicked(evt);
            }
        });
        pnErrorBank.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 70, 34));

        btClear.setText("Clear");
        btClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        pnErrorBank.add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 80, 30));

        tbErrorBank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Submit Date", "Description", "Solution", "Class", "Employee"
            }
        ));
        scpErrorBank.setViewportView(tbErrorBank);

        javax.swing.GroupLayout pnCenterLayout = new javax.swing.GroupLayout(pnCenter);
        pnCenter.setLayout(pnCenterLayout);
        pnCenterLayout.setHorizontalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(pnErrorBank, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(scpErrorBank)
        );
        pnCenterLayout.setVerticalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addComponent(pnErrorBank, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpErrorBank, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInsertMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btInsertMouseClicked

    private void btDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteMouseClicked

    private void cbClassesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbClassesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbClassesMouseClicked

    private void cbEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEmployeeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEmployeeMouseClicked

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        clearField();
    }//GEN-LAST:event_btClearActionPerformed

    private void clearField() {
        tfID.setEnabled(true);
        tfID.setEditable(true);
        tfID.setText("");
        tfSubmitDate.setText("");
        tfDescription.setText("");
        tfSolution.setText("");
        cbClasses.setSelectedIndex(0);
        cbEmployee.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btInsert;
    private javax.swing.JComboBox<String> cbClasses;
    private javax.swing.JComboBox<String> cbEmployee;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClasses;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblSolution;
    private javax.swing.JLabel lblSubmitDate;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnErrorBank;
    private javax.swing.JScrollPane scpErrorBank;
    private javax.swing.JTable tbErrorBank;
    private javax.swing.JTextField tfDescription;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfSolution;
    private javax.swing.JTextField tfSubmitDate;
    // End of variables declaration//GEN-END:variables
}
