/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author gerydanu
 */
public class ErrorBankView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AspectView
     */
    public ErrorBankView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCenter = new javax.swing.JPanel();
        pnErrorBank = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        lblSubmitDate = new javax.swing.JLabel();
        tfSubmitDate = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        tfDescription = new javax.swing.JTextField();
        lblSolution = new javax.swing.JLabel();
        tfSolution = new javax.swing.JTextField();
        lblClasses = new javax.swing.JLabel();
        cbClasses = new javax.swing.JComboBox<>();
        lblEmployee = new javax.swing.JLabel();
        cbEmployee = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        btInsert = new javax.swing.JButton();
        chbGetById = new javax.swing.JCheckBox();
        btDelete = new javax.swing.JButton();
        btSearch = new javax.swing.JButton();
        scpErrorBank = new javax.swing.JScrollPane();
        tbErrorBank = new javax.swing.JTable();

        setClosable(true);
        setTitle("Error Bank");
        setMinimumSize(new java.awt.Dimension(750, 550));
        setPreferredSize(new java.awt.Dimension(750, 550));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        pnCenter.setBackground(new java.awt.Color(153, 255, 153));
        pnCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        pnErrorBank.setBackground(new java.awt.Color(153, 255, 153));
        pnErrorBank.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setText("ID");
        pnErrorBank.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 70, 30));
        pnErrorBank.add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 1, 180, 30));

        lblSubmitDate.setText("Submit Date");
        pnErrorBank.add(lblSubmitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 70, 30));
        pnErrorBank.add(tfSubmitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 40, 180, 30));

        lblDescription.setText("Description");
        pnErrorBank.add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 70, 30));
        pnErrorBank.add(tfDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 79, 480, 30));

        lblSolution.setText("Solution");
        pnErrorBank.add(lblSolution, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 70, 30));
        pnErrorBank.add(tfSolution, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 118, 480, 30));

        lblClasses.setText("Class");
        pnErrorBank.add(lblClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 70, 30));

        cbClasses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbClassesMouseClicked(evt);
            }
        });
        pnErrorBank.add(cbClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 180, 30));

        lblEmployee.setText("Employee");
        pnErrorBank.add(lblEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 70, 30));

        cbEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbEmployeeMouseClicked(evt);
            }
        });
        pnErrorBank.add(cbEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 180, 30));
        pnErrorBank.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 560, 34));
        pnErrorBank.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 34));

        btInsert.setText("Insert");
        btInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btInsertMouseClicked(evt);
            }
        });
        pnErrorBank.add(btInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 70, 34));

        chbGetById.setBackground(new java.awt.Color(153, 255, 153));
        chbGetById.setText("Get by ID");
        chbGetById.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbGetById.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chbGetByIdMouseClicked(evt);
            }
        });
        pnErrorBank.add(chbGetById, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 80, 34));

        btDelete.setText("Delete");
        btDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDeleteMouseClicked(evt);
            }
        });
        pnErrorBank.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 70, 34));

        btSearch.setText("Search");
        btSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSearchMouseClicked(evt);
            }
        });
        pnErrorBank.add(btSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 70, 34));

        tbErrorBank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Submit Date", "Description", "Solution", "Class", "Employee"
            }
        ));
        scpErrorBank.setViewportView(tbErrorBank);

        javax.swing.GroupLayout pnCenterLayout = new javax.swing.GroupLayout(pnCenter);
        pnCenter.setLayout(pnCenterLayout);
        pnCenterLayout.setHorizontalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(pnErrorBank, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(scpErrorBank)
        );
        pnCenterLayout.setVerticalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addComponent(pnErrorBank, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpErrorBank, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbGetByIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbGetByIdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chbGetByIdMouseClicked

    private void btSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btSearchMouseClicked

    private void btInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInsertMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btInsertMouseClicked

    private void btDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteMouseClicked

    private void cbClassesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbClassesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbClassesMouseClicked

    private void cbEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEmployeeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEmployeeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btInsert;
    private javax.swing.JButton btSearch;
    private javax.swing.JComboBox<String> cbClasses;
    private javax.swing.JComboBox<String> cbEmployee;
    private javax.swing.JCheckBox chbGetById;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblClasses;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblSolution;
    private javax.swing.JLabel lblSubmitDate;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnErrorBank;
    private javax.swing.JScrollPane scpErrorBank;
    private javax.swing.JTable tbErrorBank;
    private javax.swing.JTextField tfDescription;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfSolution;
    private javax.swing.JTextField tfSubmitDate;
    // End of variables declaration//GEN-END:variables
}
