/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EvaluationController;
import controllers.LessonController;
import controllers.ParticipantController;
import controllers.RoomController;
import controllers.TopicController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Evaluation;
import models.Lesson;
import models.Participant;
import models.Topic;
import org.hibernate.Hibernate;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;

/**
 *
 * @author gerydanu
 */
public class EvaluationView extends javax.swing.JInternalFrame {
    private SessionFactory factory = HibernateUtil.getSessionFactory();
    private EvaluationController evc = new EvaluationController(factory);
    private ParticipantController prc = new ParticipantController(factory);
    private LessonController lc = new LessonController(factory);
    private TopicController tc = new TopicController(factory);
    DefaultTableModel myTableModel = new DefaultTableModel();
    private List<models.Evaluation> evaluationList = new ArrayList<>();
    private List<models.Participant> participantList = new ArrayList<>();
    private List<models.Lesson> lessonList = new ArrayList<>();
    private List<models.Topic> topicList = new ArrayList<>();

    /**
     * Creates new form AspectView
     */
    public EvaluationView() {
        initComponents();
        showParticipant();
        showLesson();
        showTopic();
        tableEvaluation(evc.getAll());
    }
    
//    void showParticipant() {
//        for (Participant participant : participantList) cbParticipant.addItem(participant.getEmployee().getName());
//    }
    
    void showParticipant() {
        for (Participant participant : prc.getAll()) {
            cbParticipant.addItem(participant.getEmployee().getName());
        }
    }
    
    void showLesson() {
//        for (Lesson lesson : lessonList) cbLesson.addItem(lesson.getName());
        for (Lesson lesson : lc.getAll()) {
            cbLesson.addItem(lesson.getName());
        }
    }
    
    void showTopic() {
//        for (Topic topic : topicList) cbTopic.addItem(topic.getName());
        for (Topic topic : tc.getAll()) {
            cbTopic.addItem(topic.getName());
        }
    }
    
    
    private void tableEvaluation(List<models.Evaluation> evaluation) {
        Object[] columnNames = {"No.", "ID", "Is Daily", "Evaluation Date", "Note", "Participant", "Lesson", "Topic"};
        Object[][] data = new Object[evaluation.size()][columnNames.length];
        for (int i = 0; i < data.length; i++) {
            data[i][0] = (i + 1);
            data[i][1] = evaluation.get(i).getId();
            data[i][2] = evaluation.get(i).getIsdaily();
            data[i][3] = evaluation.get(i).getEvaluationdate();
            data[i][4] = evaluation.get(i).getNote();
            data[i][5] = evaluation.get(i).getParticipant();
            data[i][6] = evaluation.get(i).getLesson();
            data[i][7] = evaluation.get(i).getTopic();

        }
        myTableModel = new DefaultTableModel(data, columnNames);
        tbEvaluation.setModel(myTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCenter = new javax.swing.JPanel();
        pnEvaluation = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        lblIsDaily = new javax.swing.JLabel();
        chbIsDaily = new javax.swing.JCheckBox();
        lblDate = new javax.swing.JLabel();
        tfDate = new javax.swing.JTextField();
        lblNote = new javax.swing.JLabel();
        tfNote = new javax.swing.JTextField();
        lblParticipant = new javax.swing.JLabel();
        cbParticipant = new javax.swing.JComboBox<>();
        lblLesson = new javax.swing.JLabel();
        cbLesson = new javax.swing.JComboBox<>();
        lblTopic = new javax.swing.JLabel();
        cbTopic = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btInsert = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        scpEvaluation = new javax.swing.JScrollPane();
        tbEvaluation = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 255, 153));
        setClosable(true);
        setTitle("Evaluation");
        setMinimumSize(new java.awt.Dimension(750, 550));
        setPreferredSize(new java.awt.Dimension(750, 550));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        pnCenter.setBackground(new java.awt.Color(153, 255, 153));
        pnCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        pnEvaluation.setBackground(new java.awt.Color(153, 255, 153));
        pnEvaluation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setText("ID");
        pnEvaluation.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 60, 28));
        pnEvaluation.add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 2, 230, 28));

        lblIsDaily.setText("Is Daily");
        pnEvaluation.add(lblIsDaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 60, 28));

        chbIsDaily.setBackground(new java.awt.Color(153, 255, 153));
        chbIsDaily.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbIsDaily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chbIsDailyMouseClicked(evt);
            }
        });
        pnEvaluation.add(chbIsDaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 50, 28));

        lblDate.setText("Date");
        pnEvaluation.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 28));
        pnEvaluation.add(tfDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 230, 28));

        lblNote.setText("Note");
        pnEvaluation.add(lblNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 60, 28));
        pnEvaluation.add(tfNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 550, 28));

        lblParticipant.setText("Participant");
        pnEvaluation.add(lblParticipant, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 60, 28));

        cbParticipant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbParticipantMouseClicked(evt);
            }
        });
        pnEvaluation.add(cbParticipant, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 230, 28));

        lblLesson.setText("Lesson");
        pnEvaluation.add(lblLesson, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 60, 28));

        cbLesson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbLessonMouseClicked(evt);
            }
        });
        pnEvaluation.add(cbLesson, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 230, 28));

        lblTopic.setText("Topic");
        pnEvaluation.add(lblTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 60, 28));

        cbTopic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTopicMouseClicked(evt);
            }
        });
        pnEvaluation.add(cbTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 230, 28));
        pnEvaluation.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 610, 23));

        btInsert.setText("Insert");
        btInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btInsertMouseClicked(evt);
            }
        });
        pnEvaluation.add(btInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 80, 30));

        btDelete.setText("Delete");
        btDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDeleteMouseClicked(evt);
            }
        });
        pnEvaluation.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 80, 30));

        scpEvaluation.setBackground(new java.awt.Color(153, 255, 153));

        tbEvaluation.setAutoCreateRowSorter(true);
        tbEvaluation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Is Daily", "Date", "Note", "Participant", "Lesson", "Topic"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpEvaluation.setViewportView(tbEvaluation);

        javax.swing.GroupLayout pnCenterLayout = new javax.swing.GroupLayout(pnCenter);
        pnCenter.setLayout(pnCenterLayout);
        pnCenterLayout.setHorizontalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpEvaluation, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                    .addGroup(pnCenterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnCenterLayout.setVerticalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addComponent(pnEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpEvaluation, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
        );

        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbParticipantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbParticipantMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbParticipantMouseClicked

    private void cbLessonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbLessonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLessonMouseClicked

    private void cbTopicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTopicMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTopicMouseClicked

    private void btInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInsertMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btInsertMouseClicked

    private void btDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteMouseClicked

    private void chbIsDailyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbIsDailyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chbIsDailyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btInsert;
    private javax.swing.JComboBox<String> cbLesson;
    private javax.swing.JComboBox<String> cbParticipant;
    private javax.swing.JComboBox<String> cbTopic;
    private javax.swing.JCheckBox chbIsDaily;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIsDaily;
    private javax.swing.JLabel lblLesson;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblParticipant;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnEvaluation;
    private javax.swing.JScrollPane scpEvaluation;
    private javax.swing.JTable tbEvaluation;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNote;
    // End of variables declaration//GEN-END:variables
}
