/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import models.EmployeeLanguage;
import models.Language;
import org.hibernate.SessionFactory;
import tools.*;

/**
 *
 * @author FES
 */
public class InputCVEmployeeLanguageView extends javax.swing.JInternalFrame {

    private SessionFactory factory = HibernateUtil.getSessionFactory();
    private EmployeeLanguageControllerInterface c = new EmployeeLanguageController(factory);
    private LanguageControllerInterface cl = new LanguageController(factory);
    
    private DefaultTableModel tableModel;
    private List<models.Language> languageList = new ArrayList<>();
    /**
     * Creates new form InputCVEmployeeLanguageView
     */
    public InputCVEmployeeLanguageView() {
        initComponents();
        setDefaultCondition();
    }

    private void setDefaultCondition(){
        showAllTable(c.searchWD(Session.getSession()));
        getLanguageList();
        setComboBox();
    }

    private void showAllTable(List<EmployeeLanguage> er){
        Object[] columnNames = {"Nomor", "Language"};
        Object[][] data = new Object[er.size()][columnNames.length];
        for (int i = 0; i < data.length; i++) {
            try {
                data[i][0] = (i + 1);
                data[i][1] = er.get(i).getLanguage().getName();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        tableModel = new DefaultTableModel(data, columnNames);
        tbEmpLanguage.setModel(tableModel);
    }
    
    private void getLanguageList(){
        for (Language data : cl.getAll()) {
            languageList.add(data);
        }
    }
    
    private void setComboBox(){
        for (Language data : languageList) {
            cbEmployeeLanguage.addItem(data.getId()+" - "+data.getName());
        }
    }
    
    private void getRidTheBar() {
        putClientProperty("Home.isPallete", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnMTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnMTRCenter = new javax.swing.JPanel();
        pnMTRC1 = new javax.swing.JPanel();
        lblEmployeeLanguage = new javax.swing.JLabel();
        cbEmployeeLanguage = new javax.swing.JComboBox<>();
        pnMTRC2 = new javax.swing.JPanel();
        btSave = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        pnMTRC3 = new javax.swing.JPanel();
        spcEmpLanguage = new javax.swing.JScrollPane();
        tbEmpLanguage = new javax.swing.JTable();
        pnMTBottom = new javax.swing.JPanel();
        btOke = new javax.swing.JButton();
        pnMTRight = new javax.swing.JPanel();
        pnMTLeft = new javax.swing.JPanel();

        setBorder(null);
        setTitle("Employee Language");

        pnMain.setBackground(new java.awt.Color(204, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(700, 500));
        pnMain.setLayout(new java.awt.BorderLayout(5, 5));

        pnMTop.setBackground(new java.awt.Color(204, 255, 255));
        pnMTop.setPreferredSize(new java.awt.Dimension(700, 50));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setText("Employee Language");

        javax.swing.GroupLayout pnMTopLayout = new javax.swing.GroupLayout(pnMTop);
        pnMTop.setLayout(pnMTopLayout);
        pnMTopLayout.setHorizontalGroup(
            pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnMTopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitle)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnMTopLayout.setVerticalGroup(
            pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnMTopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitle)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnMain.add(pnMTop, java.awt.BorderLayout.PAGE_START);

        pnMTRCenter.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRCenter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnMTRC1.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRC1.setPreferredSize(new java.awt.Dimension(640, 38));
        pnMTRC1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblEmployeeLanguage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmployeeLanguage.setText("Employee Language: ");
        pnMTRC1.add(lblEmployeeLanguage);

        cbEmployeeLanguage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbEmployeeLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbEmployeeLanguage.setMinimumSize(new java.awt.Dimension(30, 25));
        cbEmployeeLanguage.setPreferredSize(new java.awt.Dimension(300, 25));
        pnMTRC1.add(cbEmployeeLanguage);

        pnMTRCenter.add(pnMTRC1);

        pnMTRC2.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRC2.setPreferredSize(new java.awt.Dimension(640, 38));
        pnMTRC2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        pnMTRC2.add(btSave);

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        pnMTRC2.add(btDelete);

        pnMTRCenter.add(pnMTRC2);

        pnMTRC3.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRC3.setPreferredSize(new java.awt.Dimension(640, 300));

        spcEmpLanguage.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        spcEmpLanguage.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spcEmpLanguage.setPreferredSize(new java.awt.Dimension(640, 280));

        tbEmpLanguage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbEmpLanguage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmpLanguageMouseClicked(evt);
            }
        });
        spcEmpLanguage.setViewportView(tbEmpLanguage);

        pnMTRC3.add(spcEmpLanguage);

        pnMTRCenter.add(pnMTRC3);

        pnMain.add(pnMTRCenter, java.awt.BorderLayout.CENTER);

        pnMTBottom.setBackground(new java.awt.Color(204, 255, 255));
        pnMTBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 25, 5));

        btOke.setText("Oke");
        btOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkeActionPerformed(evt);
            }
        });
        pnMTBottom.add(btOke);

        pnMain.add(pnMTBottom, java.awt.BorderLayout.PAGE_END);

        pnMTRight.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRight.setPreferredSize(new java.awt.Dimension(20, 390));

        javax.swing.GroupLayout pnMTRightLayout = new javax.swing.GroupLayout(pnMTRight);
        pnMTRight.setLayout(pnMTRightLayout);
        pnMTRightLayout.setHorizontalGroup(
            pnMTRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnMTRightLayout.setVerticalGroup(
            pnMTRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        pnMain.add(pnMTRight, java.awt.BorderLayout.LINE_END);

        pnMTLeft.setBackground(new java.awt.Color(204, 255, 255));
        pnMTLeft.setPreferredSize(new java.awt.Dimension(20, 390));

        javax.swing.GroupLayout pnMTLeftLayout = new javax.swing.GroupLayout(pnMTLeft);
        pnMTLeft.setLayout(pnMTLeftLayout);
        pnMTLeftLayout.setHorizontalGroup(
            pnMTLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnMTLeftLayout.setVerticalGroup(
            pnMTLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        pnMain.add(pnMTLeft, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkeActionPerformed
        dispose();
    }//GEN-LAST:event_btOkeActionPerformed

    private void tbEmpLanguageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmpLanguageMouseClicked
        String temp="";
        for (Language data : languageList) {
            if (data.getName().equals(tbEmpLanguage.getValueAt(tbEmpLanguage.getSelectedRow(), 1).toString()))temp=data.getId();
        }
        for (int i = 0; i < cbEmployeeLanguage.getItemCount(); i++) {
            if (cbEmployeeLanguage.getItemAt(i).split(" - ")[0].equals(temp))
            cbEmployeeLanguage.setSelectedIndex(i);
        }
    }//GEN-LAST:event_tbEmpLanguageMouseClicked

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        c.deleteSoft("", Session.getSession(), cbEmployeeLanguage.getSelectedItem().toString().split(" - ")[0]);
        showAllTable(c.searchWD(Session.getSession()));
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        c.save("", Session.getSession(), cbEmployeeLanguage.getSelectedItem().toString().split(" - ")[0]);
        showAllTable(c.searchWD(Session.getSession()));
    }//GEN-LAST:event_btSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btOke;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbEmployeeLanguage;
    private javax.swing.JLabel lblEmployeeLanguage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnMTBottom;
    private javax.swing.JPanel pnMTLeft;
    private javax.swing.JPanel pnMTRC1;
    private javax.swing.JPanel pnMTRC2;
    private javax.swing.JPanel pnMTRC3;
    private javax.swing.JPanel pnMTRCenter;
    private javax.swing.JPanel pnMTRight;
    private javax.swing.JPanel pnMTop;
    private javax.swing.JPanel pnMain;
    private javax.swing.JScrollPane spcEmpLanguage;
    private javax.swing.JTable tbEmpLanguage;
    // End of variables declaration//GEN-END:variables
}
