/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.EmployeeRole;
import models.Role;
import models.WorkExperience;
import org.hibernate.SessionFactory;
import tools.*;

/**
 *
 * @author FES
 */
public class InputCVWorkExperienceView extends javax.swing.JInternalFrame {

    private SessionFactory factory = HibernateUtil.getSessionFactory();
    private WorkExperienceControllerInterface c = new WorkExperienceController(factory);
    
    private DefaultTableModel tableModel;
    private SimpleDateFormat dateFormatOut = new SimpleDateFormat("dd-MM-yyyy");
    
    /**
     * Creates new form InputCVWorkExperienceView
     */
    public InputCVWorkExperienceView() {
        initComponents();
        setDefaultCondition();
        
    }
    
    private void setDefaultCondition(){
        showAllTable(c.searchWD(Session.getSession()));
        dcStartDate.setDateFormat(dateFormatOut);
        dcEndDate.setDateFormat(dateFormatOut);
        tfStartDate.setEnabled(false);
        tfEndDate.setEnabled(false);

    }

    private void showAllTable(List<WorkExperience> er){
        Object[] columnNames = {"Nomor", "Name", "Start Date", "End Date", "Description"};
        Object[][] data = new Object[er.size()][columnNames.length];
        for (int i = 0; i < data.length; i++) {
            try {
                data[i][0] = (i + 1);
                data[i][1] = er.get(i).getName();
                data[i][2] = dateFormatOut.format(er.get(i).getStartdate());
                data[i][3] = dateFormatOut.format(er.get(i).getEnddate());
                data[i][4] = er.get(i).getDescription();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        tableModel = new DefaultTableModel(data, columnNames);
        tbWorkExperience.setModel(tableModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnMTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnMTRCenter = new javax.swing.JPanel();
        pnMTRC1 = new javax.swing.JPanel();
        lblEducationHis1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        pnMTRC2 = new javax.swing.JPanel();
        lblEmpCertification2 = new javax.swing.JLabel();
        dcStartDate = new datechooser.beans.DateChooserCombo();
        lblEmpCertification3 = new javax.swing.JLabel();
        dcEndDate = new datechooser.beans.DateChooserCombo();
        tfStartDate = new javax.swing.JTextField();
        tfEndDate = new javax.swing.JTextField();
        pnMTRC5 = new javax.swing.JPanel();
        lblWorkExperience2 = new javax.swing.JLabel();
        tfDescription = new javax.swing.JTextField();
        pnMTRC3 = new javax.swing.JPanel();
        btSave = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        pnMTRC4 = new javax.swing.JPanel();
        scpWorkExperience = new javax.swing.JScrollPane();
        tbWorkExperience = new javax.swing.JTable();
        pnMTBottom = new javax.swing.JPanel();
        btOke = new javax.swing.JButton();
        pnMTRight = new javax.swing.JPanel();
        pnMTLeft = new javax.swing.JPanel();

        setBorder(null);

        pnMain.setBackground(new java.awt.Color(204, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(700, 500));
        pnMain.setLayout(new java.awt.BorderLayout(5, 5));

        pnMTop.setBackground(new java.awt.Color(204, 255, 255));
        pnMTop.setPreferredSize(new java.awt.Dimension(700, 50));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setText("Work Experience");

        javax.swing.GroupLayout pnMTopLayout = new javax.swing.GroupLayout(pnMTop);
        pnMTop.setLayout(pnMTopLayout);
        pnMTopLayout.setHorizontalGroup(
            pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnMTopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitle)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnMTopLayout.setVerticalGroup(
            pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnMTopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitle)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnMain.add(pnMTop, java.awt.BorderLayout.PAGE_START);

        pnMTRCenter.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRCenter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnMTRC1.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRC1.setPreferredSize(new java.awt.Dimension(630, 35));
        pnMTRC1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        lblEducationHis1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEducationHis1.setText("Name: ");
        lblEducationHis1.setInheritsPopupMenu(false);
        pnMTRC1.add(lblEducationHis1);

        tfName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfName.setMinimumSize(new java.awt.Dimension(6, 25));
        tfName.setPreferredSize(new java.awt.Dimension(438, 25));
        pnMTRC1.add(tfName);

        pnMTRCenter.add(pnMTRC1);

        pnMTRC2.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRC2.setPreferredSize(new java.awt.Dimension(630, 35));
        pnMTRC2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmpCertification2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmpCertification2.setText("Start Date: ");
        pnMTRC2.add(lblEmpCertification2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        pnMTRC2.add(dcStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 20, -1));

        lblEmpCertification3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmpCertification3.setText("  End Date: ");
        pnMTRC2.add(lblEmpCertification3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));
        pnMTRC2.add(dcEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 20, -1));

        tfStartDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfStartDate.setMinimumSize(new java.awt.Dimension(6, 25));
        tfStartDate.setPreferredSize(new java.awt.Dimension(150, 25));
        tfStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStartDateActionPerformed(evt);
            }
        });
        pnMTRC2.add(tfStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        tfEndDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfEndDate.setMinimumSize(new java.awt.Dimension(6, 25));
        tfEndDate.setPreferredSize(new java.awt.Dimension(150, 25));
        tfEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEndDateActionPerformed(evt);
            }
        });
        pnMTRC2.add(tfEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        pnMTRCenter.add(pnMTRC2);

        pnMTRC5.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRC5.setPreferredSize(new java.awt.Dimension(640, 70));
        pnMTRC5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblWorkExperience2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWorkExperience2.setText("Description: ");
        lblWorkExperience2.setInheritsPopupMenu(false);
        pnMTRC5.add(lblWorkExperience2);

        tfDescription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDescription.setMinimumSize(new java.awt.Dimension(6, 25));
        tfDescription.setPreferredSize(new java.awt.Dimension(630, 25));
        pnMTRC5.add(tfDescription);

        pnMTRCenter.add(pnMTRC5);

        pnMTRC3.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRC3.setPreferredSize(new java.awt.Dimension(640, 38));
        pnMTRC3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        pnMTRC3.add(btSave);

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        pnMTRC3.add(btDelete);

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        pnMTRC3.add(btClear);

        pnMTRCenter.add(pnMTRC3);

        pnMTRC4.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRC4.setPreferredSize(new java.awt.Dimension(640, 170));
        pnMTRC4.setRequestFocusEnabled(false);

        scpWorkExperience.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scpWorkExperience.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbWorkExperience.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbWorkExperience.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbWorkExperienceMouseClicked(evt);
            }
        });
        scpWorkExperience.setViewportView(tbWorkExperience);

        javax.swing.GroupLayout pnMTRC4Layout = new javax.swing.GroupLayout(pnMTRC4);
        pnMTRC4.setLayout(pnMTRC4Layout);
        pnMTRC4Layout.setHorizontalGroup(
            pnMTRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMTRC4Layout.createSequentialGroup()
                .addComponent(scpWorkExperience, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnMTRC4Layout.setVerticalGroup(
            pnMTRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpWorkExperience, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        pnMTRCenter.add(pnMTRC4);

        pnMain.add(pnMTRCenter, java.awt.BorderLayout.CENTER);

        pnMTBottom.setBackground(new java.awt.Color(204, 255, 255));
        pnMTBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 25, 5));

        btOke.setText("Oke");
        btOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkeActionPerformed(evt);
            }
        });
        pnMTBottom.add(btOke);

        pnMain.add(pnMTBottom, java.awt.BorderLayout.PAGE_END);

        pnMTRight.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRight.setPreferredSize(new java.awt.Dimension(20, 390));

        javax.swing.GroupLayout pnMTRightLayout = new javax.swing.GroupLayout(pnMTRight);
        pnMTRight.setLayout(pnMTRightLayout);
        pnMTRightLayout.setHorizontalGroup(
            pnMTRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnMTRightLayout.setVerticalGroup(
            pnMTRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        pnMain.add(pnMTRight, java.awt.BorderLayout.LINE_END);

        pnMTLeft.setBackground(new java.awt.Color(204, 255, 255));
        pnMTLeft.setPreferredSize(new java.awt.Dimension(20, 390));

        javax.swing.GroupLayout pnMTLeftLayout = new javax.swing.GroupLayout(pnMTLeft);
        pnMTLeft.setLayout(pnMTLeftLayout);
        pnMTLeftLayout.setHorizontalGroup(
            pnMTLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnMTLeftLayout.setVerticalGroup(
            pnMTLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        pnMain.add(pnMTLeft, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkeActionPerformed
        dispose();
    }//GEN-LAST:event_btOkeActionPerformed

    private void tfStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStartDateActionPerformed

    private void tfEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEndDateActionPerformed

    private void tbWorkExperienceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbWorkExperienceMouseClicked
        tfName.setText(tbWorkExperience.getValueAt(tbWorkExperience.getSelectedRow(), 1).toString());
        tfStartDate.setText(tbWorkExperience.getValueAt(tbWorkExperience.getSelectedRow(), 2).toString());
        tfStartDate.setText(tbWorkExperience.getValueAt(tbWorkExperience.getSelectedRow(), 3).toString());
        tfDescription.setText(tbWorkExperience.getValueAt(tbWorkExperience.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_tbWorkExperienceMouseClicked

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        c.save("", tfName.getText(), tfDescription.getText(), tfStartDate.getText(), tfEndDate.getText(), Session.getSession());
        showAllTable(c.searchWD(Session.getSession()));
    }//GEN-LAST:event_btSaveActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        c.deleteSoft("", tfName.getText(), tfDescription.getText(), tfStartDate.getText(), tfEndDate.getText(), Session.getSession());
        showAllTable(c.searchWD(Session.getSession()));
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        tfDescription.setText("");
        tfStartDate.setText("");
        tfEndDate.setText("");
        tfName.setText("");
    }//GEN-LAST:event_btClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btOke;
    private javax.swing.JButton btSave;
    private datechooser.beans.DateChooserCombo dcEndDate;
    private datechooser.beans.DateChooserCombo dcStartDate;
    private javax.swing.JLabel lblEducationHis1;
    private javax.swing.JLabel lblEmpCertification2;
    private javax.swing.JLabel lblEmpCertification3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWorkExperience2;
    private javax.swing.JPanel pnMTBottom;
    private javax.swing.JPanel pnMTLeft;
    private javax.swing.JPanel pnMTRC1;
    private javax.swing.JPanel pnMTRC2;
    private javax.swing.JPanel pnMTRC3;
    private javax.swing.JPanel pnMTRC4;
    private javax.swing.JPanel pnMTRC5;
    private javax.swing.JPanel pnMTRCenter;
    private javax.swing.JPanel pnMTRight;
    private javax.swing.JPanel pnMTop;
    private javax.swing.JPanel pnMain;
    private javax.swing.JScrollPane scpWorkExperience;
    private javax.swing.JTable tbWorkExperience;
    private javax.swing.JTextField tfDescription;
    private javax.swing.JTextField tfEndDate;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfStartDate;
    // End of variables declaration//GEN-END:variables
}
