/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.*;
import org.hibernate.SessionFactory;
import tools.*;

/**
 *
 * @author FES
 */
public class InputCVEmployeeRoleView extends javax.swing.JInternalFrame {

    private SessionFactory factory = HibernateUtil.getSessionFactory();
    private EmployeeRoleControllerInterface c = new EmployeeRoleController(factory);
    private RoleControllerInterface cr = new RoleController(factory);

    private DefaultTableModel tableModel;
    private SimpleDateFormat dateFormatOut = new SimpleDateFormat("dd-MM-yyyy");
    
    private List<models.Role> roleList = new ArrayList<>();
    /**
     * Creates new form InputCVEmployeeRoleView
     */
    public InputCVEmployeeRoleView() {
        initComponents();
        setDefaultCondition();
        
    }
    
    private void setDefaultCondition(){
        showAllTable(c.searchWD(Session.getSession()));
        dcStartDate.setDateFormat(dateFormatOut);
        dcEndDate.setDateFormat(dateFormatOut);
        tfStartDate.setEnabled(false);
        tfEndDate.setEnabled(false);
        getRoleList();
        setComboBox();
    }

    private void showAllTable(List<EmployeeRole> er){
        Object[] columnNames = {"Nomor", "Role", "Start Date", "End Date"};
        Object[][] data = new Object[er.size()][columnNames.length];
        for (int i = 0; i < data.length; i++) {
            try {
                data[i][0] = (i + 1);
                data[i][1] = er.get(i).getRole().getName();
                data[i][2] = dateFormatOut.format(er.get(i).getStartdate());
                data[i][3] = dateFormatOut.format(er.get(i).getEnddate());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        tableModel = new DefaultTableModel(data, columnNames);
        tbEmployeeRole.setModel(tableModel);
    }
    
    private void getRoleList(){
        for (Role data : cr.getAll()) {
            roleList.add(data);
        }
    }
    
    private void setComboBox(){
        for (Role data : roleList) {
            cbEmpRole.addItem(data.getId()+" - "+data.getName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnMTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnMTRCenter = new javax.swing.JPanel();
        pnMTRC1 = new javax.swing.JPanel();
        lblRole1 = new javax.swing.JLabel();
        cbEmpRole = new javax.swing.JComboBox<>();
        pnMTRC2 = new javax.swing.JPanel();
        lblRole2 = new javax.swing.JLabel();
        lblRole3 = new javax.swing.JLabel();
        btDelete = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        dcStartDate = new datechooser.beans.DateChooserCombo();
        dcEndDate = new datechooser.beans.DateChooserCombo();
        tfEndDate = new javax.swing.JTextField();
        tfStartDate = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        pnMTRC3 = new javax.swing.JPanel();
        scpEmployeeRole = new javax.swing.JScrollPane();
        tbEmployeeRole = new javax.swing.JTable();
        pnMTBottom = new javax.swing.JPanel();
        btOke = new javax.swing.JButton();
        pnMTRight = new javax.swing.JPanel();
        pnMTLeft = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(700, 500));

        pnMain.setBackground(new java.awt.Color(204, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(700, 500));
        pnMain.setLayout(new java.awt.BorderLayout(5, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnMain.add(jPanel1, java.awt.BorderLayout.CENTER);

        pnMTop.setBackground(new java.awt.Color(204, 255, 255));
        pnMTop.setPreferredSize(new java.awt.Dimension(700, 50));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setText("Employee Role");

        javax.swing.GroupLayout pnMTopLayout = new javax.swing.GroupLayout(pnMTop);
        pnMTop.setLayout(pnMTopLayout);
        pnMTopLayout.setHorizontalGroup(
            pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
            .addGroup(pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnMTopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitle)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnMTopLayout.setVerticalGroup(
            pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnMTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnMTopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitle)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnMain.add(pnMTop, java.awt.BorderLayout.PAGE_START);

        pnMTRCenter.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRCenter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnMTRCenter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnMTRC1.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRC1.setPreferredSize(new java.awt.Dimension(640, 40));
        pnMTRC1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRole1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRole1.setText(" Role:  ");
        pnMTRC1.add(lblRole1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cbEmpRole.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbEmpRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbEmpRole.setMinimumSize(new java.awt.Dimension(56, 25));
        cbEmpRole.setName(""); // NOI18N
        cbEmpRole.setPreferredSize(new java.awt.Dimension(140, 25));
        pnMTRC1.add(cbEmpRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 167, -1));

        pnMTRCenter.add(pnMTRC1);

        pnMTRC2.setBackground(new java.awt.Color(204, 255, 255));
        pnMTRC2.setPreferredSize(new java.awt.Dimension(640, 70));
        pnMTRC2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRole2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRole2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRole2.setText("  Start Date: ");
        pnMTRC2.add(lblRole2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 25));

        lblRole3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRole3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRole3.setText("End Date:");
        pnMTRC2.add(lblRole3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, -1, -1));

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        pnMTRC2.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 25));

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        pnMTRC2.add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 25));

        dcStartDate.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    try {
        dcStartDate.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2019, 2, 9),
            new java.util.GregorianCalendar(2019, 2, 9))));
} catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
    e1.printStackTrace();
    }
    dcStartDate.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            dcStartDateOnSelectionChange(evt);
        }
    });
    dcStartDate.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            dcStartDateOnCommit(evt);
        }
    });
    pnMTRC2.add(dcStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 30, -1));

    dcEndDate.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
dcEndDate.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
    public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
        dcEndDateOnSelectionChange(evt);
    }
    });
    dcEndDate.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            dcEndDateOnCommit(evt);
        }
    });
    pnMTRC2.add(dcEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 30, -1));
    pnMTRC2.add(tfEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, 30));
    pnMTRC2.add(tfStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 120, 30));

    btSave.setText("Save");
    btSave.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btSaveActionPerformed(evt);
        }
    });
    pnMTRC2.add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, 25));

    pnMTRCenter.add(pnMTRC2);

    pnMTRC3.setPreferredSize(new java.awt.Dimension(640, 150));

    scpEmployeeRole.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
    scpEmployeeRole.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

    tbEmployeeRole.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    tbEmployeeRole.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tbEmployeeRoleMouseClicked(evt);
        }
    });
    scpEmployeeRole.setViewportView(tbEmployeeRole);

    javax.swing.GroupLayout pnMTRC3Layout = new javax.swing.GroupLayout(pnMTRC3);
    pnMTRC3.setLayout(pnMTRC3Layout);
    pnMTRC3Layout.setHorizontalGroup(
        pnMTRC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(scpEmployeeRole, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
    );
    pnMTRC3Layout.setVerticalGroup(
        pnMTRC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(scpEmployeeRole, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pnMTRCenter.add(pnMTRC3);

    pnMain.add(pnMTRCenter, java.awt.BorderLayout.CENTER);

    pnMTBottom.setBackground(new java.awt.Color(204, 255, 255));
    pnMTBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 25, 5));

    btOke.setText("Oke");
    btOke.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btOkeActionPerformed(evt);
        }
    });
    pnMTBottom.add(btOke);
    btOke.getAccessibleContext().setAccessibleName("");

    pnMain.add(pnMTBottom, java.awt.BorderLayout.PAGE_END);

    pnMTRight.setBackground(new java.awt.Color(204, 255, 255));
    pnMTRight.setPreferredSize(new java.awt.Dimension(20, 390));

    javax.swing.GroupLayout pnMTRightLayout = new javax.swing.GroupLayout(pnMTRight);
    pnMTRight.setLayout(pnMTRightLayout);
    pnMTRightLayout.setHorizontalGroup(
        pnMTRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 20, Short.MAX_VALUE)
    );
    pnMTRightLayout.setVerticalGroup(
        pnMTRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 377, Short.MAX_VALUE)
    );

    pnMain.add(pnMTRight, java.awt.BorderLayout.LINE_END);

    pnMTLeft.setBackground(new java.awt.Color(204, 255, 255));
    pnMTLeft.setPreferredSize(new java.awt.Dimension(20, 390));

    javax.swing.GroupLayout pnMTLeftLayout = new javax.swing.GroupLayout(pnMTLeft);
    pnMTLeft.setLayout(pnMTLeftLayout);
    pnMTLeftLayout.setHorizontalGroup(
        pnMTLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 20, Short.MAX_VALUE)
    );
    pnMTLeftLayout.setVerticalGroup(
        pnMTLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 377, Short.MAX_VALUE)
    );

    pnMain.add(pnMTLeft, java.awt.BorderLayout.LINE_START);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btOkeActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        c.deleteSoft("", tfStartDate.getText(), tfEndDate.getText(), Session.getSession(), cbEmpRole.getSelectedItem().toString().split(" - ")[0]);
        setDefaultCondition();
    }//GEN-LAST:event_btDeleteActionPerformed

    private void dcStartDateOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dcStartDateOnSelectionChange

    }//GEN-LAST:event_dcStartDateOnSelectionChange

    private void dcEndDateOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dcEndDateOnSelectionChange

    }//GEN-LAST:event_dcEndDateOnSelectionChange

    private void dcEndDateOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dcEndDateOnCommit
        tfEndDate.setText(dcEndDate.getText());
    }//GEN-LAST:event_dcEndDateOnCommit

    private void dcStartDateOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dcStartDateOnCommit
        tfStartDate.setText(dcStartDate.getText());
    }//GEN-LAST:event_dcStartDateOnCommit

    private void tbEmployeeRoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmployeeRoleMouseClicked
        String temp="";
        for (Role data : roleList) {
            if (data.getName().equals(tbEmployeeRole.getValueAt(tbEmployeeRole.getSelectedRow(), 1).toString()))temp=data.getId();
        }
        for (int i = 0; i < cbEmpRole.getItemCount(); i++) {
            if (cbEmpRole.getItemAt(i).split(" - ")[0].equals(temp))
            cbEmpRole.setSelectedIndex(i);
        }
        tfStartDate.setText(tbEmployeeRole.getValueAt(tbEmployeeRole.getSelectedRow(), 2).toString());
        tfEndDate.setText(tbEmployeeRole.getValueAt(tbEmployeeRole.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tbEmployeeRoleMouseClicked

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        cbEmpRole.setSelectedIndex(0);
        tfEndDate.setText("");
        tfStartDate.setText("");
    }//GEN-LAST:event_btClearActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        c.save("", tfStartDate.getText(), tfEndDate.getText(), Session.getSession(), cbEmpRole.getSelectedItem().toString().split(" - ")[0]);
        setDefaultCondition();
    }//GEN-LAST:event_btSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btOke;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbEmpRole;
    private datechooser.beans.DateChooserCombo dcEndDate;
    private datechooser.beans.DateChooserCombo dcStartDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRole1;
    private javax.swing.JLabel lblRole2;
    private javax.swing.JLabel lblRole3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnMTBottom;
    private javax.swing.JPanel pnMTLeft;
    private javax.swing.JPanel pnMTRC1;
    private javax.swing.JPanel pnMTRC2;
    private javax.swing.JPanel pnMTRC3;
    private javax.swing.JPanel pnMTRCenter;
    private javax.swing.JPanel pnMTRight;
    private javax.swing.JPanel pnMTop;
    private javax.swing.JPanel pnMain;
    private javax.swing.JScrollPane scpEmployeeRole;
    private javax.swing.JTable tbEmployeeRole;
    private javax.swing.JTextField tfEndDate;
    private javax.swing.JTextField tfStartDate;
    // End of variables declaration//GEN-END:variables
}
