/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author gerydanu
 */
public class LessonView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AspectView
     */
    public LessonView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleLesson = new javax.swing.JLabel();
        pnLesson = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lblClassType = new javax.swing.JLabel();
        cbClassType = new javax.swing.JComboBox<>();
        pnTable = new javax.swing.JPanel();
        scpLesson = new javax.swing.JScrollPane();
        tbLesson = new javax.swing.JTable();

        setClosable(true);
        getContentPane().setLayout(new java.awt.BorderLayout(20, 20));

        lblTitleLesson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleLesson.setText("LESSON");
        getContentPane().add(lblTitleLesson, java.awt.BorderLayout.PAGE_START);

        pnLesson.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        lblID.setText("ID");
        pnLesson.add(lblID);
        pnLesson.add(tfID);

        lblName.setText("Name");
        pnLesson.add(lblName);
        pnLesson.add(tfName);

        lblClassType.setText("Class Type");
        pnLesson.add(lblClassType);

        pnLesson.add(cbClassType);

        getContentPane().add(pnLesson, java.awt.BorderLayout.CENTER);

        tbLesson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Class Type"
            }
        ));
        scpLesson.setViewportView(tbLesson);

        javax.swing.GroupLayout pnTableLayout = new javax.swing.GroupLayout(pnTable);
        pnTable.setLayout(pnTableLayout);
        pnTableLayout.setHorizontalGroup(
            pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scpLesson, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        );
        pnTableLayout.setVerticalGroup(
            pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
            .addGroup(pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTableLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scpLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(pnTable, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbClassType;
    private javax.swing.JLabel lblClassType;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitleLesson;
    private javax.swing.JPanel pnLesson;
    private javax.swing.JPanel pnTable;
    private javax.swing.JScrollPane scpLesson;
    private javax.swing.JTable tbLesson;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
